markdown: kramdown
rroonga_version: 5.0.4
rroonga_release_date: 2015-07-13
active_groonga_version: 4.2.0
active_groonga_release_date: 2014-12-23

kramdown:
  enable_coderay: true
  coderay_line_numbers: table
