markdown: kramdown
rroonga_version: 6.0.7
rroonga_release_date: 2016-08-13
active_groonga_version: 4.2.1
active_groonga_release_date: 2015-09-26

kramdown:
  enable_coderay: true
  coderay_line_numbers: table
