markdown: kramdown
rroonga_version: 9.0.2
rroonga_release_date: 2019-05-10
active_groonga_version: 4.2.1
active_groonga_release_date: 2015-09-26
packnga_version: 1.0.3
packnga_release_date: 2016-11-14

kramdown:
  enable_coderay: true
  coderay_line_numbers: table
