markdown: kramdown
rroonga_version: 5.0.1
rroonga_release_date: 2015-04-14
active_groonga_version: 4.2.0
active_groonga_release_date: 2014-12-23

kramdown:
  enable_coderay: true
  coderay_line_numbers: table
