markdown: kramdown
rroonga_version: 5.0.9
rroonga_release_date: 2015-11-10
active_groonga_version: 4.2.1
active_groonga_release_date: 2015-09-26

kramdown:
  enable_coderay: true
  coderay_line_numbers: table
