markdown: kramdown
rroonga_version: 6.0.4
rroonga_release_date: 2016-06-14
active_groonga_version: 4.2.1
active_groonga_release_date: 2015-09-26

kramdown:
  enable_coderay: true
  coderay_line_numbers: table
